import car1 from "./public/images/creta.png";
import thar from "./public/images/thar.png";
import car2 from "./public/images/car2.png";


export const itemslist = [
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :'',
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
  {
    _id: "#12345",
    title: "All New Volkswagen",
    media: car1,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "active"
  },
  {
    _id: "#12345",
    title: "All New Thar",
    media :thar,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "booking"
  },
  {
    _id: "#12345",
    title: "All New Hyundai Creta",
    media: car2,
    fuel: "Petrol",
    driven: "24,000KM",
    mode: "Automatic",
    price: "Nrs. 58,00,000",
    offers: "16",
    test_drive: "12",
    favorite: "182",
    status: "sold"
  },
]